const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[character]));

async function api(path, options = {}) {
  const response = await fetch(path, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...(options.headers || {}) }, ...options });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(payload.error || 'Something went wrong.');
  return payload;
}

function routeShell(content) {
  document.body.classList.add('phase3-route-mode');
  const app = $('#app');
  app.innerHTML = `<div class="phase3-route-shell"><a class="wordmark phase3-route-wordmark" href="/"><span class="wordmark-mark">l<span>·</span></span>inguora</a>${content}</div>`;
}

function formMessage(target, message, type = 'error') { target.textContent = message; target.className = `phase3-message ${type}`; }
function passwordField(id, label) { return `<label class="phase3-field"><span>${label}</span><input id="${id}" type="password" autocomplete="new-password" /></label>`; }

function renderTeacherSetup() {
  routeShell(`<main class="phase3-auth-card"><div class="phase3-kicker">FIRST-TIME TEACHER SETUP <i></i></div><h1>Set the tone<br /><em>of your classroom.</em></h1><p class="phase3-auth-copy">Create the first teacher profile with a complete verified registration.</p><form id="phase3-setup-form" class="phase3-form"><label class="phase3-field"><span>Full name · الاسم بالكامل</span><input id="setup-full-name" type="text" autocomplete="name" minlength="2" required /></label><div class="phase3-two-col"><label class="phase3-field"><span>Email address · البريد الإلكتروني</span><input id="setup-email" type="email" autocomplete="email" required /></label><label class="phase3-field"><span>Phone number · رقم الهاتف</span><input id="setup-phone" type="tel" autocomplete="tel" minlength="7" required /></label></div><div class="phase3-two-col">${passwordField('setup-password', 'Password · كلمة المرور')} ${passwordField('setup-confirm-password', 'Confirm password · تأكيد كلمة المرور')}</div><label class="phase3-field"><span>Admin secret / bootstrap key</span><input id="setup-secret" type="password" autocomplete="off" required /></label><div id="phase3-setup-message" class="phase3-message" role="status"></div><button class="btn btn-primary phase3-submit" type="submit"><span>Create teacher profile</span><span>↗</span></button></form><p class="phase3-footnote">Every field is checked server-side. The bootstrap key is never stored in the browser.</p></main>`);
  $('#phase3-setup-form').addEventListener('submit', async (event) => { event.preventDefault(); const message = $('#phase3-setup-message'); const password = $('#setup-password').value; const confirmPassword = $('#setup-confirm-password').value; if (password !== confirmPassword) return formMessage(message, 'Passwords do not match.'); if (password.length < 8) return formMessage(message, 'Use at least 8 characters for the password.'); try { const result = await api('/api/teacher/setup', { method: 'POST', body: JSON.stringify({ fullName: $('#setup-full-name').value, email: $('#setup-email').value, phone: $('#setup-phone').value, password, confirmPassword, bootstrapSecret: $('#setup-secret').value }) }); formMessage(message, `Teacher profile created for ${result.user.fullName}. Opening your workspace…`, 'success'); setTimeout(() => { window.location.href = '/'; }, 650); } catch (error) { formMessage(message, error.message); } });
}

function renderTeacherLogin() {
  routeShell(`<main class="phase3-auth-card compact"><div class="phase3-kicker">TEACHER PORTAL <i></i></div><h1>Welcome back,<br /><em>teacher.</em></h1><p class="phase3-auth-copy">Use the username or email belonging to your Linguora teacher profile.</p><form id="phase3-login-form" class="phase3-form"><label class="phase3-field"><span>Username or email</span><input id="phase3-login-identifier" type="text" autocomplete="username" required /></label>${passwordField('phase3-login-password', 'Password')}<div id="phase3-login-message" class="phase3-message" role="status"></div><button class="btn btn-primary phase3-submit" type="submit"><span>Enter dashboard</span><span>↗</span></button></form><a class="phase3-backlink" href="/">← Back to Linguora</a></main>`);
  $('#phase3-login-form').addEventListener('submit', async (event) => { event.preventDefault(); const message = $('#phase3-login-message'); try { const result = await api('/api/auth/login', { method: 'POST', body: JSON.stringify({ identifier: $('#phase3-login-identifier').value, password: $('#phase3-login-password').value }) }); if (result.user.role !== 'teacher') throw new Error('This account is not a teacher profile.'); window.location.href = '/'; } catch (error) { formMessage(message, error.message); } });
}

function renderStudentSignup() {
  routeShell(`<main class="phase3-auth-card"><div class="phase3-kicker">STUDENT REGISTRATION <i></i></div><h1>Make space for<br /><em>the next hello.</em></h1><p class="phase3-auth-copy">Create your learner profile. Your teacher will see you in the registered student directory immediately.</p><form id="phase3-student-signup" class="phase3-form"><div class="phase3-two-col"><label class="phase3-field"><span>First name</span><input id="student-first-name" type="text" autocomplete="given-name" required /></label><label class="phase3-field"><span>Last name</span><input id="student-last-name" type="text" autocomplete="family-name" required /></label></div><label class="phase3-field"><span>Email</span><input id="student-email" type="email" autocomplete="email" required /></label><label class="phase3-field"><span>Phone / WhatsApp number</span><input id="student-phone" type="tel" autocomplete="tel" required /></label>${passwordField('student-password', 'Password · 8+ characters')}<div id="student-signup-message" class="phase3-message" role="status"></div><button class="btn btn-primary phase3-submit" type="submit"><span>Create student account</span><span>↗</span></button></form><a class="phase3-backlink" href="/student/login">Already registered? Log in →</a></main>`);
  $('#phase3-student-signup').addEventListener('submit', async (event) => { event.preventDefault(); const message = $('#student-signup-message'); try { const result = await api('/api/student/signup', { method: 'POST', body: JSON.stringify({ firstName: $('#student-first-name').value, lastName: $('#student-last-name').value, email: $('#student-email').value, phone: $('#student-phone').value, password: $('#student-password').value }) }); formMessage(message, `Welcome, ${result.user.fullName}. Opening your learner space…`, 'success'); setTimeout(() => { window.location.href = '/student'; }, 650); } catch (error) { formMessage(message, error.message); } });
}

function renderStudentLogin() {
  routeShell(`<main class="phase3-auth-card compact"><div class="phase3-kicker">STUDENT PORTAL <i></i></div><h1>Your next lesson<br /><em>is waiting.</em></h1><form id="phase3-student-login" class="phase3-form"><label class="phase3-field"><span>Email</span><input id="student-login-identifier" type="email" autocomplete="username" required /></label>${passwordField('student-login-password', 'Password')}<div id="student-login-message" class="phase3-message" role="status"></div><button class="btn btn-primary phase3-submit" type="submit"><span>Open learner space</span><span>↗</span></button></form><a class="phase3-backlink" href="/student/signup">Need an account? Sign up →</a></main>`);
  $('#phase3-student-login').addEventListener('submit', async (event) => { event.preventDefault(); const message = $('#student-login-message'); try { await api('/api/student/login', { method: 'POST', body: JSON.stringify({ identifier: $('#student-login-identifier').value, password: $('#student-login-password').value }) }); window.location.href = '/student'; } catch (error) { formMessage(message, error.message); } });
}

async function renderStudentDashboard() {
  document.body.classList.add('student-mode');
  routeShell(`<main class="student-dashboard"><header class="student-dashboard-head"><div><div class="phase3-kicker">LINGUORA / LEARNER SPACE <i></i></div><h1>Keep your<br /><em>curiosity close.</em></h1></div><button class="student-logout" id="student-logout" type="button">Log out ↗</button></header><section class="student-redemption"><div><span class="mini-label">UNLOCK A COURSE</span><h2>One code.<br /><em>A fuller world.</em></h2><p>Paste the access code your teacher gave you and your units will open instantly.</p></div><form id="redeem-form"><input id="redeem-code" type="text" placeholder="LNG-XXXX-XXXX" autocomplete="off" /><button class="btn btn-primary" type="submit"><span>Redeem code</span><span>↗</span></button><div id="redeem-message" class="phase3-message" role="status"></div></form></section><section><div class="student-section-head"><div><span class="mini-label">YOUR UNLOCKED PATHS</span><h2>Lessons with momentum.</h2></div><span id="student-course-count" class="panel-note">0 COURSES</span></div><div id="student-content" class="student-course-list"><div class="student-loading">Loading your space…</div></div></section></main>`);
  $('#student-logout').addEventListener('click', async () => { await api('/api/auth/logout', { method: 'POST' }); window.location.href = '/'; });
  $('#redeem-form').addEventListener('submit', async (event) => { event.preventDefault(); const message = $('#redeem-message'); try { await api('/api/student/redeem-code', { method: 'POST', body: JSON.stringify({ code: $('#redeem-code').value }) }); formMessage(message, 'Course unlocked. Your lessons are ready below.', 'success'); $('#redeem-code').value = ''; await refreshStudentContent(); } catch (error) { formMessage(message, error.message); } });
  await refreshStudentContent();
}

function youtubeEmbed(url = '') { const match = url.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/))([\w-]{6,})/i); return match ? `https://www.youtube-nocookie.com/embed/${match[1]}` : ''; }
function lessonMedia(lesson) { const url = String(lesson.videoUrl || ''); const embed = youtubeEmbed(url); const video = embed ? `<iframe class="student-video-frame" src="${embed}" title="${escapeHtml(lesson.title)} video" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>` : /^https?:\/\//i.test(url) ? `<video class="student-video-frame" controls preload="metadata" src="${escapeHtml(url)}"></video>` : url ? `<div class="media-file-note">Video asset: ${escapeHtml(url)}</div>` : ''; const pdf = lesson.pdfUrl ? `<a class="lesson-pdf-link" href="${escapeHtml(lesson.pdfUrl)}" target="_blank" rel="noopener">PDF study sheet ↗</a>` : ''; return video || pdf ? `<div class="student-lesson-media">${video}${pdf}</div>` : ''; }
async function refreshStudentContent() {
  const { courses } = await api('/api/student/content');
  $('#student-course-count').textContent = `${courses.length} COURSE${courses.length === 1 ? '' : 'S'}`;
  $('#student-content').innerHTML = courses.length ? courses.map((course) => `<article class="student-course-card"><div class="student-course-card-head"><span class="subject-chip chip-${escapeHtml(course.subject)}">${course.subject === 'english' ? '🇬🇧 English' : '🇪🇸 Spanish'}</span><small>${escapeHtml(course.grade)} · targeted access</small></div><h3>${escapeHtml(course.title)}</h3><div class="student-lesson-list">${course.lessons.map((lesson) => `<div class="student-lesson-row"><span class="student-lesson-number">${String(lesson.unitNumber).padStart(2, '0')}</span><span><strong>${escapeHtml(lesson.title)}</strong><small>${lesson.videoUrl ? 'Video ready' : 'Lesson'} ${lesson.pdfUrl ? '· PDF sheet ready' : ''}</small></span><span class="student-lesson-actions">${lesson.completed ? '<b class="lesson-done">✓ Complete</b>' : `<button class="lesson-complete" data-lesson-id="${lesson.id}" type="button">Mark complete</button>`}<button class="lesson-quiz" data-lesson-id="${lesson.id}" type="button">Quiz ↗</button></span></div>${lessonMedia(lesson)}`).join('')}</div><a class="certificate-link" href="/api/student/certificate/${course.id}">Download certificate ↗</a></article>`).join('') : '<div class="student-empty"><span>✦</span><strong>Your first course will appear here.</strong><small>Ask your teacher for an access code to begin.</small></div>';
  $$('.lesson-complete').forEach((button) => button.addEventListener('click', async () => { await api(`/api/student/lessons/${button.dataset.lessonId}/complete`, { method: 'POST' }); await refreshStudentContent(); }));
  $$('.lesson-quiz').forEach((button) => button.addEventListener('click', () => launchQuiz(button.dataset.lessonId)));
}

async function launchQuiz(lessonId) {
  const { attemptId, questions, total } = await api(`/api/student/quiz/${lessonId}/start`);
  const overlay = document.createElement('div'); overlay.className = 'quiz-overlay'; overlay.innerHTML = `<div class="quiz-modal"><button class="quiz-close" type="button">×</button><span class="mini-label">RANDOMIZED UNIT QUIZ</span><h2>Say it<br /><em>like you mean it.</em></h2><form id="quiz-form">${questions.map((question, index) => `<fieldset><legend><span>0${index + 1}</span>${escapeHtml(question.question)}</legend>${question.choices.map((choice) => `<label><input type="radio" name="question-${question.id}" value="${choice.key}" required /><span>${choice.key}</span>${escapeHtml(choice.text)}</label>`).join('')}</fieldset>`).join('')}<button class="btn btn-primary" type="submit"><span>Submit ${total} answers</span><span>↗</span></button><div id="quiz-message" class="phase3-message" role="status"></div></form></div>`; document.body.appendChild(overlay); $('.quiz-close', overlay).addEventListener('click', () => overlay.remove()); $('#quiz-form', overlay).addEventListener('submit', async (event) => { event.preventDefault(); const answers = Object.fromEntries(questions.map((question) => [question.id, $(`input[name="question-${question.id}"]:checked`, overlay)?.value])); const result = await api(`/api/student/quiz/${attemptId}/submit`, { method: 'POST', body: JSON.stringify({ answers }) }); formMessage($('#quiz-message', overlay), result.passed ? 'Perfect score. Your certificate is now available after progress is complete.' : `You scored ${result.score}/${result.total}. Review the lesson and try again.`, result.passed ? 'success' : 'error'); if (result.passed) setTimeout(() => { overlay.remove(); refreshStudentContent(); }, 1200); });
}

async function renderTeacherTools() {
  if (!$('#dashboard-panel-overview') || $('#phase3-teacher-tools')) return;
  $('#dashboard-panel-overview .metric-grid').insertAdjacentHTML('afterend', '<article class="dashboard-card phase3-persistence-card" id="phase3-teacher-tools"><div class="targeting-heading"><span class="mini-label">TARGETED ACCESS CONTROL</span><h3>Give the right learner the right path.</h3><p>Choose a subject, grade, exact courses or modules, and a validity window.</p></div><div class="targeting-grid"><label class="phase3-field"><span>Target subject</span><select id="code-subject"><option value="spanish">🇪🇸 Spanish</option><option value="english">🇬🇧 English</option></select></label><label class="phase3-field"><span>Grade level</span><select id="code-grade"><option>الصف الأول الثانوي</option><option>الصف الثاني الثانوي</option><option>الصف الثالث الثانوي</option></select></label><label class="phase3-field"><span>Unlock mode</span><select id="code-scope"><option value="specific">Specific courses / modules</option><option value="all">All content for this grade</option></select></label><label class="phase3-field"><span>Validity</span><select id="code-duration"><option value="7">7 days</option><option value="30" selected>30 days</option><option value="90">90 days</option><option value="365">Full academic year</option></select></label><div class="target-option-box" id="code-target-options"><span class="mini-label">SELECT UNITS</span><div id="code-course-options">Loading courses…</div></div><div class="phase3-code-actions"><button class="btn btn-primary" id="phase3-generate-code" type="button"><span>Generate targeted code</span><span>↗</span></button><strong id="phase3-generated-code"></strong><div id="phase3-code-message" class="phase3-message"></div></div></div><div class="code-history"><div class="dashboard-card-head"><div><span class="mini-label">CODE HISTORY</span><h3>Active invitations.</h3></div><span class="panel-note">EXPIRY AWARE <i></i></span></div><div class="code-history-wrap"><table class="code-history-table"><thead><tr><th>Code</th><th>Target</th><th>Validity</th><th>Status</th></tr></thead><tbody id="phase3-code-history"></tbody></table></div></div></article>');
  const { courses } = await api('/api/teacher/courses'); const subject = $('#code-subject'); const grade = $('#code-grade'); const scope = $('#code-scope');
  const renderOptions = () => { const matches = courses.filter((course) => course.subject === subject.value && course.grade === grade.value); $('#code-target-options').classList.toggle('is-all', scope.value === 'all'); $('#code-course-options').innerHTML = scope.value === 'all' ? '<p class="target-all-copy">All matching courses and modules will unlock.</p>' : (matches.length ? matches.map((course) => `<label class="target-course-check"><input type="checkbox" value="${course.id}" data-target-course /><span><strong>${escapeHtml(course.title)}</strong><small>${course.lessonCount} lessons</small></span></label>${course.modules.map((module) => `<label class="target-module-check"><input type="checkbox" value="${module.id}" data-target-module /><span>Unit ${module.unitNumber} · ${escapeHtml(module.title)} <small>${module.lessonCount} lessons</small></span></label>`).join('')}`).join('') : '<p class="target-all-copy">No matching content yet. Create a lesson for this subject and grade first.</p>'); };
  [subject, grade, scope].forEach((control) => control.addEventListener('change', renderOptions)); renderOptions();
  const historyBody = $('#phase3-code-history'); const renderHistory = async () => { const { codes } = await api('/api/teacher/access-codes'); historyBody.innerHTML = codes.length ? codes.map((code) => `<tr><td><strong>${escapeHtml(code.code)}</strong></td><td>${escapeHtml(code.targetSubject)} · ${escapeHtml(code.targetGrade)}<small>${code.unlockScope === 'all' ? 'All grade content' : `${(code.targetCourseIds || []).length + (code.targetModuleIds || []).length} selected target(s)`}</small></td><td>${new Date(code.expiresAt).toLocaleDateString('en-GB', { day: '2-digit', month: 'short' })}</td><td><span class="code-status status-${code.status}">${code.status}</span></td></tr>`).join('') : '<tr><td colspan="4" class="table-empty">No codes generated yet.</td></tr>'; }; await renderHistory();
  $('#phase3-generate-code').addEventListener('click', async () => { const message = $('#phase3-code-message'); const courseIds = $$('[data-target-course]:checked').map((input) => Number(input.value)); const moduleIds = $$('[data-target-module]:checked').map((input) => Number(input.value)); try { const result = await api('/api/teacher/access-codes', { method: 'POST', body: JSON.stringify({ targetSubject: subject.value, targetGrade: grade.value, unlockScope: scope.value, courseIds, moduleIds, duration: $('#code-duration').value }) }); $('#phase3-generated-code').textContent = result.code; formMessage(message, `Expires ${new Date(result.expiresAt).toLocaleDateString('en-GB')}.`, 'success'); await renderHistory(); } catch (error) { formMessage(message, error.message); } });
}

async function syncTeacherDashboard() {
  try {
    const [overview, directory, me, courseData] = await Promise.all([api('/api/teacher/overview'), api('/api/teacher/students'), api('/api/me'), api('/api/teacher/courses')]);
    if (me.user?.fullName && $('#teacher-display-name')) $('#teacher-display-name').textContent = me.user.fullName;
    const values = { students: overview.students, codes: overview.codes, views: overview.views, average: `${overview.average}%` };
    Object.entries(values).forEach(([key, value]) => { const node = document.querySelector(`[data-metric="${key}"]`); if (node) node.textContent = value; });
    const body = $('#student-table-body'); if (body) { body.innerHTML = directory.students.map((student, index) => `<tr><td><span class="student-person"><i class="student-avatar avatar-${index % 4}">${escapeHtml(student.fullName.split(' ').map((part) => part[0]).join('').slice(0, 2))}</i><strong>${escapeHtml(student.fullName)}</strong></span></td><td>${escapeHtml(student.email || '')}</td><td>${escapeHtml(student.phone)}</td><td>${new Date(student.registrationDate).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}</td><td><span class="course-count">${student.enrolledCourses} courses</span></td><td><span class="course-count">${student.activatedCodes} codes</span></td><td><button class="row-more" type="button">···</button></td></tr>`).join('') || '<tr><td colspan="7" class="table-empty">No students yet.</td></tr>'; $('#student-count').textContent = directory.students.length; }
    const recent = $('#recent-lessons-content'); const lessons = courseData.courses.flatMap((course) => (course.lessons || []).map((lesson) => ({ ...lesson, subject: course.subject }))).slice(0, 5); if (recent && lessons.length) recent.innerHTML = '<div class="recent-row recent-head"><span>LESSON</span><span>SUBJECT</span><span>MEDIA</span><span>STATUS</span></div>' + lessons.map((lesson) => `<div class="recent-row"><span><strong>${escapeHtml(lesson.title)}</strong><small>Unit ${String(lesson.unitNumber).padStart(2, '0')}</small></span><span class="subject-chip chip-${escapeHtml(lesson.subject)}">${lesson.subject === 'english' ? '🇬🇧 English' : '🇪🇸 Spanish'}</span><span>${lesson.videoUrl ? 'Video' : 'Lesson'}${lesson.pdfUrl ? ' · PDF' : ''}</span><span class="status-live">Published</span></div>`).join('');
    await renderTeacherTools();
  } catch (error) { console.warn('Phase 3 dashboard sync:', error.message); }
}

function bindHomeAuth() {
  const teacherForm = $('#teacher-form');
  if (teacherForm) {
    $('#admin-username').value = '';
    $('#admin-password').value = '';
    teacherForm.addEventListener('submit', async (event) => { event.preventDefault(); event.stopImmediatePropagation(); const message = $('#form-message'); try { const result = await api('/api/auth/login', { method: 'POST', body: JSON.stringify({ identifier: $('#admin-username').value, password: $('#admin-password').value }) }); if (result.user.role !== 'teacher') throw new Error('Use the student portal for learner accounts.'); if (window.openDashboard) window.openDashboard(); await syncTeacherDashboard(); } catch (error) { formMessage(message, error.message); } }, true);
  }
  api('/api/setup/status').then(({ teacherExists }) => { if (!teacherExists) $$('.teacher-trigger').forEach((button) => button.addEventListener('click', (event) => { event.preventDefault(); event.stopImmediatePropagation(); window.location.href = '/teacher/setup'; }, true)); }).catch(() => {});
  $$('#student-portal, #student-header-portal, #closing-cta').forEach((button) => button.addEventListener('click', (event) => { event.preventDefault(); event.stopImmediatePropagation(); window.location.href = '/student/signup'; }, true));
  const logout = $('#dashboard-logout'); if (logout) logout.addEventListener('click', async (event) => { event.preventDefault(); event.stopImmediatePropagation(); await api('/api/auth/logout', { method: 'POST' }); window.location.href = '/'; }, true);
  const lessonForm = $('#lesson-form'); if (lessonForm) lessonForm.addEventListener('submit', async (event) => { event.preventDefault(); event.stopImmediatePropagation(); const feedback = $('#lesson-feedback'); try { const result = await api('/api/teacher/lessons', { method: 'POST', body: JSON.stringify({ subject: document.querySelector('input[name="lesson-subject"]:checked')?.value || 'spanish', grade: $('#lesson-grade').value, unitNumber: Number($('#lesson-unit').value || 1), title: $('#lesson-title').value, videoUrl: $('#lesson-youtube').value || $('#lesson-video-file').files[0]?.name || '', pdfUrl: $('#lesson-pdf').files[0]?.name || '', coverUrl: $('#lesson-cover').files[0]?.name || '', rawQuestions: $('#question-source')?.value || '' }) }); formMessage(feedback, `Saved “${result.lesson.title}” to the database. ${result.questionCount} questions attached.`, 'success'); await syncTeacherDashboard(); setTimeout(() => document.querySelector('[data-dashboard-tab="overview"]')?.click(), 700); } catch (error) { formMessage(feedback, error.message); } }, true);
  const videoInput = $('#lesson-video-file'); const pdfInput = $('#lesson-pdf');
  if (videoInput) videoInput.addEventListener('change', () => { const file = videoInput.files[0]; if (!file) return; let preview = $('#phase3-video-preview'); if (!preview) { preview = document.createElement('video'); preview.id = 'phase3-video-preview'; preview.className = 'cms-media-preview'; preview.controls = true; videoInput.closest('.video-source-field').appendChild(preview); } preview.src = URL.createObjectURL(file); });
  if (pdfInput) pdfInput.addEventListener('change', () => { const file = pdfInput.files[0]; if (!file) return; let preview = $('#phase3-pdf-preview'); if (!preview) { preview = document.createElement('iframe'); preview.id = 'phase3-pdf-preview'; preview.className = 'cms-pdf-preview'; pdfInput.closest('.file-row').after(preview); } preview.title = 'Study sheet preview'; preview.src = URL.createObjectURL(file); });

}

export function initPhase3() {
  const route = window.location.pathname.replace(/\/$/, '') || '/';
  if (route === '/teacher/setup') return renderTeacherSetup();
  if (route === '/teacher/login') return renderTeacherLogin();
  if (route === '/student/signup') return renderStudentSignup();
  if (route === '/student/login') return renderStudentLogin();
  if (route === '/student') { renderStudentDashboard().catch((error) => { routeShell(`<main class="phase3-auth-card compact"><h1>Sign in to<br /><em>your space.</em></h1><p>${escapeHtml(error.message)}</p><a class="btn btn-primary" href="/student/login">Student login ↗</a></main>`); }); return; }
  bindHomeAuth();
  api('/api/me').then(({ user }) => { if (user?.role === 'teacher' && window.openDashboard) { window.openDashboard(); syncTeacherDashboard(); } if (user?.role === 'student') window.location.href = '/student'; }).catch(() => {});
}
